epid-ubuntu-16.04:
  tags:
    - sgx
  image: ratls-ubuntu16.04
  only:
    - web
    - schedules
  script:
    - ./build.sh sgxsdk
    - ./build.sh graphene
    - ./build.sh sgxlkl
    - make -C apps/secret-provisioning-example
    - make check

epid-ubuntu-18.04:
  tags:
    - sgx
  image: ratls-ubuntu18.04
  only:
    - web
    - schedules
  script:
    - ./build.sh sgxsdk
    - ./build.sh graphene
    - ./build.sh sgxlkl
    - make -C apps/secret-provisioning-example
    - make check

ecdsa-ubuntu-16.04:
  tags:
    - sgx-ecdsa
  image: ratls-ubuntu16.04
  only:
    - web
    - schedules
  script:
    - ECDSA=1 ./build.sh graphene
    - ECDSA=1 make wolfssl-ra-attester
    - ECDSA=1 make wolfssl-ra-challenger
    - make -C deps/SGXDataCenterAttestationPrimitives/SampleCode/QuoteServiceSample
    - ECDSA=1 make check

ecdsa-ubuntu-18.04:
  tags:
    - sgx-ecdsa
  image: ratls-ubuntu18.04
  only:
    - web
    - schedules
  script:
    - ECDSA=1 ./build.sh graphene
    - ECDSA=1 make wolfssl-ra-attester
    - ECDSA=1 make wolfssl-ra-challenger
    - make -C deps/SGXDataCenterAttestationPrimitives/SampleCode/QuoteServiceSample
    - ECDSA=1 make check
